# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielens_app', '0002_auto_20170321_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
