# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielens_app', '0004_auto_20170321_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
