# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:56
from __future__ import unicode_literals
import csv
from django.db import migrations
from ..models import Movie, Rater, Rating

def load_movies(apps, schema_editor):
    Movie = apps.get_model("movieratings_app", "Movie")
    datafile_PATH = 'u.item'

    with open(datafile_PATH, 'r', encoding="latin-1") as f:
        cats = {'fieldnames': ('movie_id', 'title', 'release_date', 'imdb_link')}
        reader = csv.DictReader(f, **cats, delimiter = '|')
        for row in reader:
            m = Movie(id=row['movie_id'], title=row['title'], release_date=row['release_date'], imdb_link=row['imdb_link'])
            m.save()


def load_raters(apps, schema_editor):
    Rater = apps.get_model("movieratings_app", "Rater")
    datafile_PATH = 'u.user'

    with open(datafile_PATH, 'r', encoding="latin-1") as f:
        cats = {'fieldnames': ('rater_id', 'age', 'gender', 'occupation', 'zip_code'), 'delimiter': ('|')}
        reader = csv.DictReader(f, **cats)
        for row in reader:
            r = Rater(id=row['rater_id'], age=row['age'], gender=row['gender'], occupation=row['occupation'], zip_code=row['zip_code'])
            r.save()


def load_ratings(apps, schema_editor):
    Rating = apps.get_model("movieratings_app", "Rating")
    Rater = apps.get_model("movieratings_app", "Rater")
    Movie = apps.get_model("movieratings_app", "Movie")
    datafile_PATH = 'u.data'

# this rating.movie_id must be a movie instance
    with open(datafile_PATH, 'r', encoding="latin-1") as f:
        cats = {'fieldnames': ('rater_id', 'movie_id', 'rating', 'timestamp'), 'delimiter': '\t'}
        reader = csv.DictReader(f, **cats)
        for row in reader:
            m = Movie.objects.get(id=row['movie_id'])
            rater = Rater.objects.get(id=row['rater_id'])
            r = Rating(rating=row['rating'], timestamp=row['timestamp'], movie=m, rater=rater)
            r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movielens_app', '0005_remove_movie_genre'),
    ]

    operations = [
        migrations.RunPython(load_movie),
        migrations.RunPython(load_rater),
        migrations.RunPython(load_rating),
    ]
